version: "1.1"
spec:
  servicePort: 80
  hostname: ""
  sharedDir:
    path: /var/www/html
    storage: "5Gi"
  podTemplate:
    containers:
      - name: php
        image: "devpanel/nodejs:16-base"
        env:
          - name: "APP_ROOT"
            value: "/var/www/html"
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
        resources:
          requests:
            memory: 256Mi
            cpu: 50m
          limits:
            memory: 2Gi
            cpu: 500m
